### ISSUE TITLE
chatty-discord fails to deserialize mentioned roles

### ISSUE THREAD

**Issue by Dragas** [Dragas/bIRC#15]
```java
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 188 path $.d.mention_roles[0] 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.Gson.fromJson(Gson.java:887) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.Gson.fromJson(Gson.java:852) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.Gson.fromJson(Gson.java:801) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.Gson.fromJson(Gson.java:773) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at lt.saltyjuice.dragas.chatty.v3.discord.adapter.DiscordAdapter.getFromJson(DiscordAdapter.kt:138) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at lt.saltyjuice.dragas.chatty.v3.discord.adapter.DiscordAdapter.deserialize(DiscordAdapter.kt:85) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at lt.saltyjuice.dragas.chatty.v3.discord.adapter.DiscordAdapter.decode(DiscordAdapter.kt:79) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at lt.saltyjuice.dragas.chatty.v3.discord.adapter.DiscordAdapter.decode(DiscordAdapter.kt:18) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.tyrus.core.TyrusEndpointWrapper.decodeCompleteMessage(TyrusEndpointWrapper.java:439) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:571) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:879) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:216) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:139) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:807) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:747) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:476) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:114) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:272) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:283) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:200) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:132) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:111) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:536) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at java.lang.Thread.run(Thread.java:745) 
Aug 26 20:43:27 bork-236 app/worker.1: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 188 path $.d.mention_roles[0] 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) 
Aug 26 20:43:27 bork-236 app/worker.1: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) 
Aug 26 20:43:27 bork-236 app/worker.1: 	... 40 more 
```
as seen on heroku.

**Comment by Dragas** [comment]
fixed in 9d0302b31eeaed84dad148cb10c6071f11ab5a0d
